-- ============================================================
--  Gans E-Scooter Demand Pipeline — Database Schema
-- ============================================================
--  Run this ONCE in a SQL client (MySQL Workbench, SQLTools,
--  the mysql CLI, ...) to create the database and its tables.
--  The Python notebook then fills these tables with data.
--
--  Design idea:
--    * `cities` holds STATIC facts (one row per city).
--    * Everything else (populations, weather, flights, events)
--      is time-varying and links back to a city via `city_id`,
--      a FOREIGN KEY pointing at the cities PRIMARY KEY.
--    * Splitting it this way keeps the data clean and lets us
--      keep history instead of overwriting.
-- ============================================================

CREATE DATABASE IF NOT EXISTS gans;
USE gans;


-- ------------------------------------------------------------
--  cities — static facts that don't change (the parent table)
-- ------------------------------------------------------------
CREATE TABLE cities (
    city_id      INT AUTO_INCREMENT,     -- surrogate key, generated by MySQL
    cityname     VARCHAR(100),           -- must match the DataFrame column exactly
    country      VARCHAR(100),
    area_km2     FLOAT,
    elevation_m  FLOAT,
    latitude     FLOAT,
    longitude    FLOAT,
    PRIMARY KEY (city_id)
);


-- ------------------------------------------------------------
--  populations — population measured over time
--  (separate from cities so we can keep a dated history)
-- ------------------------------------------------------------
CREATE TABLE populations (
    population_id  INT AUTO_INCREMENT,
    city_id        INT,                  -- which city this measurement belongs to
    population     INT,
    recorded_on    DATE,                 -- when the figure was recorded
    PRIMARY KEY (population_id),
    FOREIGN KEY (city_id) REFERENCES cities(city_id)
);


-- ------------------------------------------------------------
--  weather — 5-day / 3-hour forecast per city (a time series)
-- ------------------------------------------------------------
CREATE TABLE weather (
    weather_id        INT AUTO_INCREMENT,
    city_id           INT,
    forecast_time     DATETIME,          -- the 3-hour forecast slot
    temperature       FLOAT,
    feels_like        FLOAT,
    humidity          INT,
    description       VARCHAR(100),
    wind_speed        FLOAT,
    rain_probability  FLOAT,
    rain_mm           FLOAT,
    PRIMARY KEY (weather_id),
    FOREIGN KEY (city_id) REFERENCES cities(city_id)
);


-- ------------------------------------------------------------
--  flights — tomorrow's arrivals at each city's airport
-- ------------------------------------------------------------
CREATE TABLE flights (
    flight_id      INT AUTO_INCREMENT,
    city_id        INT,
    arrival_time   DATETIME,
    flight_number  VARCHAR(20),
    airline        VARCHAR(100),
    origin_airport VARCHAR(150),
    origin_iata    VARCHAR(10),
    aircraft       VARCHAR(100),
    PRIMARY KEY (flight_id),
    FOREIGN KEY (city_id) REFERENCES cities(city_id)
);


-- ------------------------------------------------------------
--  events — upcoming concerts & shows per city
-- ------------------------------------------------------------
CREATE TABLE events (
    event_id    INT AUTO_INCREMENT,
    city_id     INT,
    event_name  VARCHAR(300),            -- event titles get long
    event_date  DATE,
    event_time  TIME,
    category    VARCHAR(100),            -- Music, Sports, Arts & Theatre, ...
    genre       VARCHAR(100),
    venue_name  VARCHAR(300),
    venue_city  VARCHAR(100),
    PRIMARY KEY (event_id),
    FOREIGN KEY (city_id) REFERENCES cities(city_id)
);


-- ============================================================
--  Handy reset (run if you want to start the data fresh).
--  Child tables MUST be cleared before the parent because of
--  the foreign keys — order matters.
-- ============================================================
-- DELETE FROM events;
-- DELETE FROM flights;
-- DELETE FROM weather;
-- DELETE FROM populations;
-- DELETE FROM cities;


-- ============================================================
--  Example analysis query: which cities have the most going on
--  tomorrow (flights + events combined)?
-- ============================================================
-- SELECT  c.cityname,
--         COUNT(DISTINCT f.flight_id) AS arrivals,
--         COUNT(DISTINCT e.event_id)  AS events
-- FROM        cities  c
-- LEFT JOIN   flights f ON c.city_id = f.city_id
-- LEFT JOIN   events  e ON c.city_id = e.city_id
-- GROUP BY    c.cityname
-- ORDER BY    arrivals DESC;
